config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'meist', to: 'pages#meist'
  resources :contacts, only: :create
  get 'kontakt', to: 'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
   
   validates :name, presence: true
   validates :email, presence: true
   validates :comments, presence: true
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

   def new
      @contact = Contact.new
   end
   
   def create
      
      @contact = Contact.new(contact_params)
      if @contact.save
         name = params[:contact][:name]
         email = params[:contact][:email]
         body = params[:contact][:comments]
         ContactMailer.contact_email(name, email, body).deliver
         
         flash[:success] = "Teade saadetud!"       # flash[:success] - key (html'isapplication bootstrap class'i nimi); "Teade saadetud!" - väärtus
         redirect_to new_contact_path#, notice: "Teade saadetud!"    selle osa asemel vt. eelmine rida
      else
         flash[:danger] = "Kõik väljad peavad olema täidetud!"  #@contact.errors.full_messages.join(", ") <- kuidas muuta ingliskeelset errors'i teksti iga välja kohta ankeedis?
         redirect_to new_contact_path#, notice: "Saatmisel tekkis viga."
      end
      
   end
   
   private
      def contact_params
         params.require(:contact).permit(:name, :email, :comments)      # need v2ljad peavad olema t2idetud
      end
   
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   def home
   end
   
   def meist
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
   <div class="row">
      
      <h3 class="text-center">Võtke ühendust</h3>
         
      <div class="col-md-4 col-md-offset-4">
         
         <%#= flash[:notice] %>  <!-- peale andmete sisestamist väljastab ekraanile teksti, mis kirjutatud contacts_controller.rb faili -->
         <%#= flash[:success] %> <!-- väljastab flash hashi salvestatud teksti -->
         <%#= flash[:error] %>
         
         
         
         <!-- Kogu kupatus l2heb application.html.erb faili! -->
         
         <%# flash.each do |type, msg| %>  <!-- tsükkel, mis võtab bootstrapist iga key väärtuse järgi klassi, 
                                        väljastab sõnumi vastava kujundusega. Võrdusmärk ees puudub, sest see rida ei väljasta midagi! 
                                        type - key, msg - value  key-value paarid ruby keeles! contacts_controller.rb flash-hash -->
            <%#= content_tag :div, msg, class: "alert alert-#{type}" %>
         <%# end %>
         
         
         
         <!-- <%#= form_for "/contacts" do |f| %>  -->
         <%= form_for @contact do |f| %>  <!-- @contact viib ankeeti sisestatud andmed conntacts_controller faili, kus luuakse nende põhjal uus objekt -->
           
            <div class="form-group">
               <%= f.text_field :name, class: 'form-control', placeholder: 'Nimi' %>
            </div>
            
            <div class="form-group">
               <%= f.text_field :email, class: 'form-control', placeholder: 'E-post' %>
            </div>
            
            <div class="form-group">
               <!-- <%= f.label :comments, 'Kommentaar' %> -->
               <%= f.text_area :comments, class: 'form-control', placeholder: 'Kommentaar' %>
            </div>
            
            <div class="form-group">
               <%= f.submit 'Saada', class: 'btn btn-block btn-kontakt' %>
            </div>
            
         <% end %>
        
      </div> <!-- col-md-4 -->
      
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title>Skarabeus</title>
      <%= csrf_meta_tags %>
      <link href="https://fonts.googleapis.com/css?family=Arvo:400,400i,700,700i" rel="stylesheet">
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   </head>

   <body>
    
      <nav class="navbar navbar-default navbar-static-top" role="navigation">
         <div class='container'>
            
            <div class="navbar-header">
               
               <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
               </button>
               
               <!-- <a href="/" class="navbar-brand"><i class="fa fa-bug"></i> Skarabeus</a>  HTML viisil linkide tegemine-->
               <!-- %= link_to "/", class: "navbar-brand" do %>     Rails viisil linkide tegemine-->
               <%= link_to root_path, class: "navbar-brand" do %>   <!--prefiksiga link 'root_path', vt. 'root_url'-->
                  <i class="fa fa-bug"></i>
                  Skarabeus
               <% end %>
               
            </div><!-- /.navbar-header -->
           
            <div class="collapse navbar-collapse" id="main-nav-collapse">
               <ul class="nav navbar-nav navbar-right">
                  <!-- <li><a href="/meist">Meist</a></li>    '/meist' on routes.rb failis 'meist' lehe asukoht -->
                  <!-- <li><%= link_to "Meist", "/meist" %></li>   Rails viisil linkide tegemine -->
                  <li><%= link_to "Meist", meist_path %></li> <!-- prefiksiga link 'meist_path'  vt. 'meist_url'-->
                  <li><%= link_to "Kontakt", new_contact_path %></li>
               </ul>
            </div><!-- /.navbar-collapse -->
            
         </div><!-- /.container -->
      </nav>
    
    
      <!-- Flash sõnumid on arukas panna application.html.erb faili,
         kuna peale ankeedi täitmist suunatakse uuele lehele (nt konto tegemisel kasutaja konto avalehele vms.)
         (vt contacts_controller.rb faili). 
         Nii on kuvatavad teated alati näha, olenemata sellest, mis lehele kasutaja edasi suunati. -->
         
      <div class="container">
         
         <% flash.each do |type, msg| %>  <!-- tsükkel, mis võtab bootstrapist iga key väärtuse järgi klassi, 
                                           väljastab sõnumi vastava kujundusega. Võrdusmärk ees puudub, sest see rida ei väljasta midagi! 
                                           type - key, msg - value  key-value paarid ruby keeles! contacts_controller.rb flash-hash -->
            <%#= content_tag :div, msg, class: "alert alert-#{type}" %>
            
            <div class="alert alert-<%= "#{type}" %>" >
               <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
               <%= "#{msg}" %>
            </div>
           
         <% end %>
         
      </div><!-- /.container -->
      
      <%= yield %>
      
   </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
   <h1>Skarabeus</h1>
   <h3>Ehtne käsitöö parimatelt ehtekunstnikelt!</h3>
</div>

app/views/pages/meist.html.erb
<div class="container text-center">
   
   <h1>About page</h1>
   
   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis similique, 
   asperiores ut dignissimos, quis nam soluta ipsa sapiente ipsum earum. Incidunt 
   rerum placeat, fuga doloremque! Ratione reprehenderit ducimus, distinctio beatae.</p>

</div>